### ISSUE TITLE
Feature Request: Mutually Exclusive Links

### ISSUE THREAD

**Issue by 321nick** [emipa606/LinkableSettings#6]
can there be an option for mutually exclusive linkeables? one good use for this is in SD medic addons, where the addons have different tiers, but all tiers can benefit a single bed. so you can have spacer surgery tools, and then ontop of those you have industrial and medieval, which for some reason still give a buff aswell, which IMHO doesnt make sense (spacer tools would make those tiers redundant, no?)

**Comment by emipa606** [comment]
Based on the description of the Medic Addons description, the support for multiple addons are intended and that its up to the user to use it responsibly. 
Not sure how to implement a feature such as this in a good way, it would probably be better handled in each respective mod to solve.
